// Status: reconstructed. Project-specific configuration for the local UpperView prototype.
(function (global) {
  global.HomePlannerConfig = {
    meta: {
      status: "reconstructed",
      source: "Recovered UpperView HomePlanner frontend plus inferred local data",
      notes: "Original UpperView PHP data was not captured. Neutral reconstructed catalog data is used."
    },
    builder: {
      id: 1,
      key: "upperview",
      name: "UpperView",
      dir: "upperview",
      website: "https://www.upperviewhomes.com/",
      logo: "",
      altLogo: "",
      phone: "",
      email: "",
      designApp: 1,
      parentId: "",
      selfDir: "",
      disclaimer: "",
      contact: { firstName: "", lastName: "", email: "" },
      analyticsId: "UA-46999026-29",
      facebookAppId: "944621658936860",
      fbPostUrl: ""
    },
    project: {
      id: 1,
      key: "grandview-trail",
      name: "Grandview Trail",
      city: "Oshawa",
      state: "ON",
      targetNeighborhood: "Grandview Trail"
    },
    designer: {
      contentStorage: "cloudinary",
      pageOrder: "0,1,2,3,12,5,6,8,9",
      bgColor: "E5F0B8",
      displayIntPhotos: "001",
      displayExtPhotos: "001",
      bundle: "",
      customRegMsg: "",
      requireRegister: 0,
      designButtonOnly: 0,
      plansSubtitle: "",
      elevTitleSqft: "",
      elevTitleBr: "",
      elevTitleBath: "",
      omitCityInBrochure: 0,
      omitLocationFilter: 0,
      showFilters: 1,
      presetPlanFilter: "",
      showPlansCount: 1,
      useMetric: 0,
      lotSort: "",
      allCommunitiesLabel: "All Communities",
      availableCommunitiesLabel: "Available Communities",
      showAvailableHomes: 0,
      showBrochureElevDetails: 0,
      showBrochureNbrhoodDetails: 0,
      plainStart: 0,
      showCities: 0,
      showAvailableCommunities: 0,
      communityIsColorScheme: 0,
      showAllBtn: 0,
      nbrhoodsBg: "",
      allPlansImage: "",
      inventoryImage: "",
      designMeImage: "",
      quickMoveinLabel: "Quick Move-In",
      splashAllBtnHide: 0,
      splashAllBtnTxt: "",
      splashAllBtnSubtxt: "",
      splashAllBtnImage: "",
      splashAllBtnVerb: "",
      splashDsnBtnHide: 0,
      splashDsnBtnTxt: "",
      splashDsnBtnSubtxt: "",
      splashDsnBtnImage: "",
      splashDsnBtnVerb: "",
      splashInvBtnHide: 0,
      splashInvBtnTxt: "",
      splashInvBtnSubtxt: "",
      splashInvBtnImage: "",
      splashInvBtnVerb: "",
      crm: {
        enabled: false,
        LassoUID: "",
        ClientID: "",
        ProjectID: "",
        community: "",
        planName: "",
        domainAccountId: "",
        renderingApp: "",
        renderingAppAnswer: ""
      }
    },
    communities: [
      {
        id: 1,
        key: "grandview-trail",
        name: "Grandview Trail",
        caption: "Grandview Trail",
        description: "Grandview Trail is a warm and family-friendly community located within North Oshawa.",
        city: "Oshawa",
        state: "ON",
        metro: "Grandview Trail",
        metroId: 1,
        latitude: 43.945,
        longitude: -78.837,
        pricingEnabled: true,
        colorMethod: "PALETTE",
        defaultCommunity: true,
        salesApp: true,
        active: true,
        sort: "Name",
        order: "asc",
        lotType: "lot",
        logo: "",
        site: "",
        cutsheet: "",
        thumb: "",
        imgs: "",
        crmId: 0,
        url: "https://www.upperviewhomes.com/",
        addr1: "",
        addr2: "",
        numInv: 3,
        numHomeSitesOnly: 4,
        numPlans: 3,
        numElevs: 6,
        minSqft: 1985,
        maxSqft: 3125,
        minBed: 3,
        maxBed: 5,
        minBath: 2.5,
        maxBath: 4,
        minPrice: 734990,
        maxPrice: 929990,
        landPhotoFolder: "",
        landPhotos: [],
        siteplan: {
          id: 1,
          status: "reconstructed",
          image: "",
          width: 180,
          height: 132,
          coordinateSystem: "legacy-percent",
          note: "Reconstructed homesite boxes exercise the recovered siteplan flow; no original UpperView siteplan artwork was recovered."
        },
        legend: [
          { id: 1, code: "available", name: "Available", color: "#8bbf40", selectable: 1, available: 1, status: "reconstructed" },
          { id: 2, code: "hold", name: "On Hold", color: "#f0b84a", selectable: 0, available: 0, status: "reconstructed" },
          { id: 3, code: "sold", name: "Sold", color: "#8b8b8b", selectable: 0, available: 0, status: "reconstructed" },
          { id: 4, code: "inventory", name: "Quick Move-In", color: "#4a90c2", selectable: 1, available: 1, isInventory: 1, status: "reconstructed" },
          { id: 5, code: "model", name: "Model Home", color: "#b06fc5", selectable: 1, available: 0, isModel: 1, status: "reconstructed" }
        ],
        lots: [
          {
            id: 1,
            label: "Reconstructed Lot 1",
            name: "1",
            landId: 1,
            status: "reconstructed",
            sold: "available",
            statusLabel: "Available",
            selectable: 1,
            available: 1,
            x: 18,
            y: 22,
            width: 24,
            height: 36,
            frontage: 36,
            depth: 98,
            size: "36 ft x 98 ft",
            orientation: "north",
            planId: 101,
            elevId: 1001,
            cost: 0,
            premium: 12000,
            address: "Reconstructed Homesite 1",
            lotType: "lot",
            mls: "",
            landMls: "",
            photoFolder: "",
            compatiblePlanIds: "101,102",
            restrictedPlanIds: "103",
            allowedElevationIds: "1001,1002,1003,1004",
            restrictionReason: "Reconstructed narrower lot excludes the largest sample plan.",
            quickMoveIn: 0,
            modelHome: 0,
            inventoryId: "",
            availableDate: "To be built",
            homeStyle: "Detached"
          },
          {
            id: 2,
            label: "Reconstructed Lot 2",
            name: "2",
            landId: 2,
            status: "reconstructed",
            sold: "inventory",
            statusLabel: "Quick Move-In",
            selectable: 1,
            available: 1,
            x: 48,
            y: 22,
            width: 24,
            height: 36,
            frontage: 40,
            depth: 101,
            size: "40 ft x 101 ft",
            orientation: "north",
            planId: 102,
            elevId: 1003,
            cost: 849990,
            premium: 18000,
            address: "Reconstructed Quick Move-In 2",
            lotType: "lot",
            mls: "RECON-MLS-9001",
            landMls: "RECON-LAND-2",
            photoFolder: "",
            compatiblePlanIds: "102",
            restrictedPlanIds: "",
            allowedElevationIds: "1003",
            restrictionReason: "Inventory home is already assigned to one reconstructed plan/elevation.",
            quickMoveIn: 1,
            modelHome: 0,
            inventoryId: 9001,
            availableDate: "Immediate",
            homeStyle: "Detached Quick Move-In"
          },
          {
            id: 3,
            label: "Reconstructed Lot 3",
            name: "3",
            landId: 3,
            status: "reconstructed",
            sold: "hold",
            statusLabel: "On Hold",
            selectable: 0,
            available: 0,
            x: 78,
            y: 22,
            width: 24,
            height: 36,
            frontage: 44,
            depth: 104,
            size: "44 ft x 104 ft",
            orientation: "north",
            planId: 103,
            elevId: 1005,
            cost: 0,
            premium: 15000,
            address: "Reconstructed Homesite 3",
            lotType: "lot",
            mls: "",
            landMls: "",
            photoFolder: "",
            compatiblePlanIds: "102,103",
            restrictedPlanIds: "101",
            allowedElevationIds: "1003,1004,1005,1006",
            restrictionReason: "Reconstructed hold shows temporarily unavailable homesite behavior.",
            quickMoveIn: 0,
            modelHome: 0,
            inventoryId: "",
            availableDate: "Hold",
            homeStyle: "Detached"
          },
          {
            id: 4,
            label: "Reconstructed Lot 4",
            name: "4",
            landId: 4,
            status: "reconstructed",
            sold: "model",
            statusLabel: "Model Home",
            selectable: 1,
            available: 0,
            x: 18,
            y: 70,
            width: 24,
            height: 36,
            frontage: 40,
            depth: 96,
            size: "40 ft x 96 ft",
            orientation: "south",
            planId: 101,
            elevId: 1002,
            cost: 0,
            premium: 0,
            address: "Reconstructed Model Home",
            lotType: "lot",
            mls: "",
            landMls: "",
            photoFolder: "",
            compatiblePlanIds: "101",
            restrictedPlanIds: "102,103",
            allowedElevationIds: "1002",
            restrictionReason: "Model home is fixed to the sample model elevation.",
            quickMoveIn: 0,
            modelHome: 1,
            inventoryId: "",
            availableDate: "Model only",
            homeStyle: "Model Home"
          },
          {
            id: 5,
            label: "Reconstructed Lot 5",
            name: "5",
            landId: 5,
            status: "reconstructed",
            sold: "sold",
            statusLabel: "Sold",
            selectable: 0,
            available: 0,
            x: 48,
            y: 70,
            width: 24,
            height: 36,
            frontage: 38,
            depth: 99,
            size: "38 ft x 99 ft",
            orientation: "south",
            planId: 102,
            elevId: 1004,
            cost: 0,
            premium: 0,
            address: "Reconstructed Sold Homesite",
            lotType: "lot",
            mls: "",
            landMls: "",
            photoFolder: "",
            compatiblePlanIds: "101,102",
            restrictedPlanIds: "103",
            allowedElevationIds: "1001,1002,1003,1004",
            restrictionReason: "Sold lot is retained for legend and unavailable-state testing.",
            quickMoveIn: 0,
            modelHome: 0,
            inventoryId: "",
            availableDate: "Sold",
            homeStyle: "Detached"
          },
          {
            id: 6,
            label: "Reconstructed Lot 6",
            name: "6",
            landId: 6,
            status: "reconstructed",
            sold: "inventory",
            statusLabel: "Quick Move-In",
            selectable: 1,
            available: 1,
            x: 78,
            y: 70,
            width: 24,
            height: 36,
            frontage: 46,
            depth: 108,
            size: "46 ft x 108 ft",
            orientation: "south",
            planId: 103,
            elevId: 1006,
            cost: 939990,
            premium: 22000,
            address: "Reconstructed Quick Move-In 6",
            lotType: "lot",
            mls: "RECON-MLS-9002",
            landMls: "RECON-LAND-6",
            photoFolder: "",
            compatiblePlanIds: "103",
            restrictedPlanIds: "",
            allowedElevationIds: "1006",
            restrictionReason: "Inventory home is already assigned to one reconstructed plan/elevation.",
            quickMoveIn: 1,
            modelHome: 0,
            inventoryId: 9002,
            availableDate: "Immediate",
            homeStyle: "Family Suite Quick Move-In"
          },
          {
            id: 7,
            label: "Reconstructed Lot 7",
            name: "7",
            landId: 7,
            status: "reconstructed",
            sold: "available",
            statusLabel: "Available",
            selectable: 1,
            available: 1,
            x: 108,
            y: 22,
            width: 24,
            height: 36,
            frontage: 50,
            depth: 112,
            size: "50 ft x 112 ft",
            orientation: "north",
            planId: 103,
            elevId: 1005,
            cost: 0,
            premium: 26000,
            address: "Reconstructed Premium Homesite 7",
            lotType: "lot",
            mls: "",
            landMls: "",
            photoFolder: "",
            compatiblePlanIds: "101,102,103",
            restrictedPlanIds: "",
            allowedElevationIds: "1001,1002,1003,1004,1005,1006",
            restrictionReason: "",
            quickMoveIn: 0,
            modelHome: 0,
            inventoryId: "",
            availableDate: "To be built",
            homeStyle: "Detached"
          },
          {
            id: 8,
            label: "Reconstructed Lot 8",
            name: "8",
            landId: 8,
            status: "reconstructed",
            sold: "available",
            statusLabel: "Available",
            selectable: 1,
            available: 1,
            x: 108,
            y: 70,
            width: 24,
            height: 36,
            frontage: 34,
            depth: 92,
            size: "34 ft x 92 ft",
            orientation: "south",
            planId: 101,
            elevId: 1001,
            cost: 0,
            premium: 8000,
            address: "Reconstructed Narrow Homesite 8",
            lotType: "lot",
            mls: "",
            landMls: "",
            photoFolder: "",
            compatiblePlanIds: "101",
            restrictedPlanIds: "102,103",
            allowedElevationIds: "1001,1002",
            restrictionReason: "Reconstructed narrow homesite accepts only the smallest sample plan.",
            quickMoveIn: 0,
            modelHome: 0,
            inventoryId: "",
            availableDate: "To be built",
            homeStyle: "Detached"
          },
          {
            id: 9,
            label: "Reconstructed Lot 9",
            name: "9",
            landId: 9,
            status: "reconstructed",
            sold: "inventory",
            statusLabel: "Quick Move-In",
            selectable: 1,
            available: 1,
            x: 138,
            y: 46,
            width: 24,
            height: 36,
            frontage: 42,
            depth: 105,
            size: "42 ft x 105 ft",
            orientation: "east",
            planId: 101,
            elevId: 1001,
            cost: 779990,
            premium: 10000,
            address: "Reconstructed Quick Move-In 9",
            lotType: "lot",
            mls: "RECON-MLS-9003",
            landMls: "RECON-LAND-9",
            photoFolder: "",
            compatiblePlanIds: "101",
            restrictedPlanIds: "",
            allowedElevationIds: "1001",
            restrictionReason: "Inventory home is already assigned to one reconstructed plan/elevation.",
            quickMoveIn: 1,
            modelHome: 0,
            inventoryId: 9003,
            availableDate: "60 days",
            homeStyle: "Starter Quick Move-In"
          }
        ],
        inventory: [
          { id: 9001, lotId: 2, lotName: "2", planId: 102, planName: "Reconstructed Plan B", elevId: 1003, elevName: "A", price: 849990, cost: 849990, status: "inventory", availabilityStatus: "quick-move-in", address: "Reconstructed Quick Move-In 2", addr: "Reconstructed Quick Move-In 2", mlsId: "RECON-MLS-9001", homeStyle: "Detached Quick Move-In", sqft: 2512, bedrooms: 4, bathrooms: 3, availableDate: "Immediate", description: "Reconstructed quick move-in example for local runtime testing.", includedOptionIds: "2001,2003" },
          { id: 9002, lotId: 6, lotName: "6", planId: 103, planName: "Reconstructed Plan C", elevId: 1006, elevName: "B", price: 939990, cost: 939990, status: "inventory", availabilityStatus: "quick-move-in", address: "Reconstructed Quick Move-In 6", addr: "Reconstructed Quick Move-In 6", mlsId: "RECON-MLS-9002", homeStyle: "Family Suite Quick Move-In", sqft: 3125, bedrooms: 5, bathrooms: 4, availableDate: "Immediate", description: "Reconstructed larger quick move-in example for local runtime testing.", includedOptionIds: "2004,2005" },
          { id: 9003, lotId: 9, lotName: "9", planId: 101, planName: "Reconstructed Plan A", elevId: 1001, elevName: "A", price: 779990, cost: 779990, status: "inventory", availabilityStatus: "quick-move-in", address: "Reconstructed Quick Move-In 9", addr: "Reconstructed Quick Move-In 9", mlsId: "RECON-MLS-9003", homeStyle: "Starter Quick Move-In", sqft: 1985, bedrooms: 3, bathrooms: 2.5, availableDate: "60 days", description: "Reconstructed starter quick move-in example for route and relationship testing.", includedOptionIds: "2001,2005" }
        ],
        agent: { id: 1, firstName: "", lastName: "", email: "", phone: "" },
        standardFeatures: [
          {
            id: 1,
            name: "Community",
            features: [
              { id: 1, name: "Reconstructed sample data for local prototype only" }
            ]
          }
        ]
      }
    ],
    catalog: {
      status: "reconstructed",
      vendors: [
        { id: 1, name: "Reconstructed Exterior Vendor" },
        { id: 2, name: "Reconstructed Finish Vendor" }
      ],
      colors: [
        { id: 1, vendorId: 1, ident: "white", name: "White", hex: "FFFFFF" },
        { id: 2, vendorId: 1, ident: "black", name: "Black", hex: "000000" },
        { id: 3, vendorId: 1, ident: "gray", name: "Gray", hex: "808080" },
        { id: 4, vendorId: 1, ident: "bluegray", name: "Blue Gray", hex: "708090" },
        { id: 5, vendorId: 1, ident: "warmtaupe", name: "Warm Taupe", hex: "9B8B7A" },
        { id: 6, vendorId: 1, ident: "deepnavy", name: "Deep Navy", hex: "243A52" },
        { id: 7, vendorId: 2, ident: "lightoak", name: "Light Oak", hex: "C6A77B" },
        { id: 8, vendorId: 2, ident: "charcoalbrick", name: "Charcoal Brick", hex: "3B3B3B" }
      ],
      filterCats: [
        { id: 1, name: "Bedrooms", filters: [{ id: 11, name: "3 Bedrooms" }, { id: 12, name: "4 Bedrooms" }, { id: 13, name: "5 Bedrooms" }] },
        { id: 2, name: "Home Type", filters: [{ id: 21, name: "Two Storey" }, { id: 22, name: "Family Suite" }] },
        { id: 3, name: "Availability", filters: [{ id: 31, name: "To Be Built" }, { id: 32, name: "Quick Move-In" }] }
      ],
      palettes: [
        {
          id: 1,
          name: "Reconstructed Light Exterior Palette",
          layid: 1,
          lay: "Exterior",
          blend: "m",
          elements: [{ id: 1, colorId: 1 }, { id: 2, colorId: 5 }, { id: 3, colorId: 7 }]
        },
        {
          id: 2,
          name: "Reconstructed Contrast Exterior Palette",
          layid: 1,
          lay: "Exterior",
          blend: "m",
          elements: [{ id: 1, colorId: 3 }, { id: 2, colorId: 2 }, { id: 3, colorId: 8 }]
        },
        {
          id: 3,
          name: "Reconstructed Coastal Exterior Palette",
          layid: 1,
          lay: "Exterior",
          blend: "m",
          elements: [{ id: 1, colorId: 4 }, { id: 2, colorId: 6 }, { id: 3, colorId: 1 }]
        }
      ],
      schemes: [
        {
          id: 1,
          name: "Reconstructed Warm Neutral Scheme",
          cost: 0,
          elements: [
            { id: 1, blend: "m", colorId: 5, label: "Body Colour", palId: 1, palSelId: 1, overlayName: "", ovl: "", swatch: "" },
            { id: 2, blend: "m", colorId: 1, label: "Trim Colour", palId: 1, palSelId: 2, overlayName: "", ovl: "", swatch: "" },
            { id: 3, blend: "m", colorId: 7, label: "Accent Finish", palId: 1, palSelId: 3, overlayName: "", ovl: "", swatch: "" }
          ]
        },
        {
          id: 2,
          name: "Reconstructed Modern Contrast Scheme",
          cost: 8500,
          elements: [
            { id: 1, blend: "m", colorId: 3, label: "Body Colour", palId: 2, palSelId: 4, overlayName: "", ovl: "", swatch: "" },
            { id: 2, blend: "m", colorId: 2, label: "Trim Colour", palId: 2, palSelId: 5, overlayName: "", ovl: "", swatch: "" },
            { id: 3, blend: "m", colorId: 8, label: "Masonry Finish", palId: 2, palSelId: 6, overlayName: "", ovl: "", swatch: "" }
          ]
        },
        {
          id: 3,
          name: "Reconstructed Blue Gray Scheme",
          cost: 6500,
          elements: [
            { id: 1, blend: "m", colorId: 4, label: "Body Colour", palId: 3, palSelId: 7, overlayName: "", ovl: "", swatch: "" },
            { id: 2, blend: "m", colorId: 6, label: "Trim Colour", palId: 3, palSelId: 8, overlayName: "", ovl: "", swatch: "" },
            { id: 3, blend: "m", colorId: 1, label: "Accent Finish", palId: 3, palSelId: 9, overlayName: "", ovl: "", swatch: "" }
          ]
        }
      ],
      plans: [
        {
          id: 101,
          communityIds: [1],
          name: "Reconstructed Plan A",
          description: "Reconstructed two-storey starter family plan for local app-flow testing only.",
          videoUrl: "",
          defaultFloor: 1,
          imgs: "",
          fpimgs: "",
          fpPhotos: "",
          photos: "",
          tags: ["reconstructed", "3 Bedrooms", "Two Storey", "To Be Built"],
          filterIds: "11,21,31",
          status: "reconstructed",
          pricingStatus: "reconstructed",
          availabilityStatus: "to-be-built",
          defaultPlan: true,
          elevations: [
            {
              id: 1001,
              caption: "A",
              tag: "A",
              description: "Reconstructed traditional elevation.",
              thumb: "",
              thumbLg: "",
              base: "",
              baseImg: "",
              baseUrl: "",
              imgs: "",
              fpimgs: "",
              photos: "",
              bedrooms: 3,
              bathrooms: 2.5,
              squareFeet: 1985,
              garageSpaces: 2,
              basePrice: 734990,
              floorCount: 2,
              defaultFloor: 1,
              schemeIds: [1, 2],
              elements: [{ id: 1, name: "Body Colour", src: "" }, { id: 2, name: "Trim Colour", src: "" }, { id: 3, name: "Accent Finish", src: "" }],
              paletteOverlays: [],
              availableInCommunityIds: [1],
              status: "reconstructed",
              pricingStatus: "reconstructed",
              availabilityStatus: "available"
            },
            {
              id: 1002,
              caption: "B",
              tag: "B",
              description: "Reconstructed upgraded elevation.",
              thumb: "",
              thumbLg: "",
              base: "",
              baseImg: "",
              baseUrl: "",
              imgs: "",
              fpimgs: "",
              photos: "",
              bedrooms: 3,
              bathrooms: 2.5,
              squareFeet: 2040,
              garageSpaces: 2,
              basePrice: 749990,
              floorCount: 2,
              defaultFloor: 1,
              schemeIds: [1, 3],
              elements: [{ id: 1, name: "Body Colour", src: "" }, { id: 2, name: "Trim Colour", src: "" }, { id: 3, name: "Accent Finish", src: "" }],
              paletteOverlays: [],
              availableInCommunityIds: [1],
              status: "reconstructed",
              pricingStatus: "reconstructed",
              availabilityStatus: "model"
            }
          ]
        },
        {
          id: 102,
          communityIds: [1],
          name: "Reconstructed Plan B",
          description: "Reconstructed mid-size family plan with optional main-floor flex space.",
          videoUrl: "",
          defaultFloor: 1,
          imgs: "",
          fpimgs: "",
          fpPhotos: "",
          photos: "",
          tags: ["reconstructed", "4 Bedrooms", "Two Storey", "Quick Move-In"],
          filterIds: "12,21,32",
          status: "reconstructed",
          pricingStatus: "reconstructed",
          availabilityStatus: "quick-move-in",
          defaultPlan: false,
          elevations: [
            {
              id: 1003,
              caption: "A",
              tag: "A",
              description: "Reconstructed brick-forward elevation.",
              thumb: "",
              thumbLg: "",
              base: "",
              baseImg: "",
              baseUrl: "",
              imgs: "",
              fpimgs: "",
              photos: "",
              bedrooms: 4,
              bathrooms: 3,
              squareFeet: 2512,
              garageSpaces: 2,
              basePrice: 807990,
              floorCount: 2,
              defaultFloor: 1,
              schemeIds: [1, 2, 3],
              elements: [{ id: 1, name: "Body Colour", src: "" }, { id: 2, name: "Trim Colour", src: "" }, { id: 3, name: "Masonry Finish", src: "" }],
              paletteOverlays: [],
              availableInCommunityIds: [1],
              status: "reconstructed",
              pricingStatus: "reconstructed",
              availabilityStatus: "quick-move-in"
            },
            {
              id: 1004,
              caption: "B",
              tag: "B",
              description: "Reconstructed contemporary elevation.",
              thumb: "",
              thumbLg: "",
              base: "",
              baseImg: "",
              baseUrl: "",
              imgs: "",
              fpimgs: "",
              photos: "",
              bedrooms: 4,
              bathrooms: 3.5,
              squareFeet: 2595,
              garageSpaces: 2,
              basePrice: 824990,
              floorCount: 2,
              defaultFloor: 1,
              schemeIds: [2, 3],
              elements: [{ id: 1, name: "Body Colour", src: "" }, { id: 2, name: "Trim Colour", src: "" }, { id: 3, name: "Masonry Finish", src: "" }],
              paletteOverlays: [],
              availableInCommunityIds: [1],
              status: "reconstructed",
              pricingStatus: "reconstructed",
              availabilityStatus: "sold"
            }
          ]
        },
        {
          id: 103,
          communityIds: [1],
          name: "Reconstructed Plan C",
          description: "Reconstructed larger family-suite plan for stress testing catalog behavior.",
          videoUrl: "",
          defaultFloor: 1,
          imgs: "",
          fpimgs: "",
          fpPhotos: "",
          photos: "",
          tags: ["reconstructed", "5 Bedrooms", "Family Suite", "Quick Move-In"],
          filterIds: "13,22,32",
          status: "reconstructed",
          pricingStatus: "reconstructed",
          availabilityStatus: "quick-move-in",
          defaultPlan: false,
          elevations: [
            {
              id: 1005,
              caption: "A",
              tag: "A",
              description: "Reconstructed family-suite elevation.",
              thumb: "",
              thumbLg: "",
              base: "",
              baseImg: "",
              baseUrl: "",
              imgs: "",
              fpimgs: "",
              photos: "",
              bedrooms: 5,
              bathrooms: 4,
              squareFeet: 3040,
              garageSpaces: 2,
              basePrice: 899990,
              floorCount: 2,
              defaultFloor: 1,
              schemeIds: [1, 3],
              elements: [{ id: 1, name: "Body Colour", src: "" }, { id: 2, name: "Trim Colour", src: "" }, { id: 3, name: "Accent Finish", src: "" }],
              paletteOverlays: [],
              availableInCommunityIds: [1],
              status: "reconstructed",
              pricingStatus: "reconstructed",
              availabilityStatus: "on-hold"
            },
            {
              id: 1006,
              caption: "B",
              tag: "B",
              description: "Reconstructed premium family-suite elevation.",
              thumb: "",
              thumbLg: "",
              base: "",
              baseImg: "",
              baseUrl: "",
              imgs: "",
              fpimgs: "",
              photos: "",
              bedrooms: 5,
              bathrooms: 4,
              squareFeet: 3125,
              garageSpaces: 2,
              basePrice: 929990,
              floorCount: 2,
              defaultFloor: 1,
              schemeIds: [2, 3],
              elements: [{ id: 1, name: "Body Colour", src: "" }, { id: 2, name: "Trim Colour", src: "" }, { id: 3, name: "Masonry Finish", src: "" }],
              paletteOverlays: [],
              availableInCommunityIds: [1],
              status: "reconstructed",
              pricingStatus: "reconstructed",
              availabilityStatus: "quick-move-in"
            }
          ]
        }
      ],
      colorPackages: [
        {
          id: 1,
          name: "Reconstructed Warm Neutral Scheme",
          status: "reconstructed",
          elements: [{ id: 1, name: "Body Colour", colorId: 5 }, { id: 2, name: "Trim Colour", colorId: 1 }, { id: 3, name: "Accent Finish", colorId: 7 }]
        },
        {
          id: 2,
          name: "Reconstructed Modern Contrast Scheme",
          status: "reconstructed",
          elements: [{ id: 1, name: "Body Colour", colorId: 3 }, { id: 2, name: "Trim Colour", colorId: 2 }, { id: 3, name: "Masonry Finish", colorId: 8 }]
        },
        {
          id: 3,
          name: "Reconstructed Blue Gray Scheme",
          status: "reconstructed",
          elements: [{ id: 1, name: "Body Colour", colorId: 4 }, { id: 2, name: "Trim Colour", colorId: 6 }, { id: 3, name: "Accent Finish", colorId: 1 }]
        }
      ],
      options: [
        {
          id: 2000,
          name: "Reconstructed Base First Floor",
          type: "base",
          status: "reconstructed",
          floorNumber: 1,
          src: "floorplan-placeholder.svg",
          src2: "",
          base: true,
          listOrder: 0,
          renderOrder: 0,
          opt: false,
          cost: 0,
          size: 0,
          groupIds: "",
          fpAlts: [],
          description: "",
          href: "",
          dependent: "",
          dependentGroupIds: "",
          primary: 0,
          choiceId: "",
          excludeIds: "",
          includeIds: "",
          sku: "",
          pricingStatus: "reconstructed",
          availabilityStatus: "reconstructed"
        },
        {
          id: 2001,
          name: "Reconstructed Open Layout Option",
          type: "structural",
          status: "reconstructed",
          floorNumber: 1,
          src: "",
          src2: "",
          base: false,
          listOrder: 1,
          renderOrder: 1,
          opt: true,
          cost: 0,
          size: 0,
          groupIds: "1",
          fpAlts: [],
          description: "Neutral reconstructed option for local app-flow testing.",
          href: "",
          dependent: "",
          dependentGroupIds: "",
          primary: 0,
          choiceId: "",
          excludeIds: "",
          includeIds: "",
          sku: "",
          pricingStatus: "reconstructed",
          availabilityStatus: "reconstructed"
        },
        {
          id: 2003,
          name: "Reconstructed Main-Floor Flex Room",
          type: "structural",
          status: "reconstructed",
          floorNumber: 1,
          src: "",
          src2: "",
          base: false,
          listOrder: 2,
          renderOrder: 2,
          opt: true,
          cost: 18500,
          size: 120,
          groupIds: "1",
          fpAlts: [],
          description: "Reconstructed main-floor flex room option.",
          href: "",
          dependent: "",
          dependentGroupIds: "",
          primary: 0,
          choiceId: "main-floor-flex",
          excludeIds: "2004",
          includeIds: "",
          sku: "RECON-FLEX-1",
          pricingStatus: "reconstructed",
          availabilityStatus: "available"
        },
        {
          id: 2004,
          name: "Reconstructed Guest Suite",
          type: "structural",
          status: "reconstructed",
          floorNumber: 1,
          src: "",
          src2: "",
          base: false,
          listOrder: 3,
          renderOrder: 3,
          opt: true,
          cost: 42500,
          size: 210,
          groupIds: "1",
          fpAlts: [{ id: 3004, src: "", status: "reconstructed" }],
          description: "Reconstructed guest-suite option for larger-plan behavior testing.",
          href: "",
          dependent: "",
          dependentGroupIds: "",
          primary: 0,
          choiceId: "guest-suite",
          excludeIds: "2003",
          includeIds: "",
          sku: "RECON-SUITE-1",
          pricingStatus: "reconstructed",
          availabilityStatus: "available"
        },
        {
          id: 2002,
          name: "Reconstructed Base Second Floor",
          type: "base",
          status: "reconstructed",
          floorNumber: 2,
          src: "floorplan-placeholder.svg",
          src2: "",
          base: true,
          listOrder: 0,
          renderOrder: 0,
          opt: false,
          cost: 0,
          size: 0,
          groupIds: "",
          fpAlts: [],
          description: "",
          href: "",
          dependent: "",
          dependentGroupIds: "",
          primary: 0,
          choiceId: "",
          excludeIds: "",
          includeIds: "",
          sku: "",
          pricingStatus: "reconstructed",
          availabilityStatus: "reconstructed"
        },
        {
          id: 2005,
          name: "Reconstructed Upper Laundry",
          type: "structural",
          status: "reconstructed",
          floorNumber: 2,
          src: "",
          src2: "",
          base: false,
          listOrder: 1,
          renderOrder: 1,
          opt: true,
          cost: 9500,
          size: 45,
          groupIds: "2",
          fpAlts: [],
          description: "Reconstructed second-floor laundry option.",
          href: "",
          dependent: "2002",
          dependentGroupIds: "2",
          primary: 0,
          choiceId: "upper-laundry",
          excludeIds: "",
          includeIds: "2002",
          sku: "RECON-LAUNDRY-2",
          pricingStatus: "reconstructed",
          availabilityStatus: "available"
        },
        {
          id: 2006,
          name: "Reconstructed Ensuite Upgrade",
          type: "finish",
          status: "reconstructed",
          floorNumber: 2,
          src: "",
          src2: "",
          base: false,
          listOrder: 2,
          renderOrder: 2,
          opt: true,
          cost: 14500,
          size: 0,
          groupIds: "2",
          fpAlts: [],
          description: "Reconstructed ensuite finish upgrade.",
          href: "",
          dependent: "",
          dependentGroupIds: "",
          primary: 0,
          choiceId: "ensuite-upgrade",
          excludeIds: "",
          includeIds: "",
          sku: "RECON-ENSUITE-2",
          pricingStatus: "reconstructed",
          availabilityStatus: "available"
        }
      ],
      floorplanGroups: [
        { id: 1, floorNumber: 1, groupType: "structural", name: "First Floor Options", designatedPrimary: 0, optionIds: [2001, 2003, 2004] },
        { id: 2, floorNumber: 2, groupType: "structural", name: "Second Floor Options", designatedPrimary: 0, optionIds: [2005, 2006] }
      ],
      interiors: [],
      rendering: {
        floorplanUri: "app/upperview/images/floorplan-placeholder.svg"
      }
    },
    workflow: {
      defaultPageOrder: "0,1,2,3,12,5,6,8,9",
      buyerStateKeys: [
        "selectedCommunityId",
        "selectedPlanId",
        "selectedElevationId",
        "selectedSchemeId",
        "selectedFloorplanOptions",
        "selectedLotId",
        "leadProfile",
        "favorites"
      ]
    },
    api: {
      mode: "static-generated",
      routes: [
        { match: "/homedesigner/getclientdata.php", local: "data/generated/homedesigner/getclientdata.generated.xml", fallback: "data/reconstructed/homedesigner/getclientdata.reconstructed.xml", format: "xml", status: "generated" },
        { match: "/db/scripts/php/getcolorlib.php", local: "data/generated/db/scripts/php/getcolorlib.generated.xml", fallback: "data/reconstructed/db/scripts/php/getcolorlib.reconstructed.xml", format: "xml", status: "generated" },
        { match: "/db/scripts/php/getsummary.php", local: "data/generated/db/scripts/php/getsummary.generated.json", fallback: "data/reconstructed/db/scripts/php/getsummary.reconstructed.json", format: "json", status: "generated" },
        { match: "/db/scripts/php/getnbrhoodsdata.php", local: "data/generated/db/scripts/php/getnbrhoodsdata.generated.xml", fallback: "data/reconstructed/db/scripts/php/getnbrhoodsdata.reconstructed.xml", format: "xml", status: "generated" },
        { match: "/db/scripts/php/getplans.php", local: "data/generated/db/scripts/php/getplans.generated.xml", fallback: "data/reconstructed/db/scripts/php/getplans.reconstructed.xml", format: "xml", status: "generated" },
        { match: "/db/scripts/php/getElevationDetails.php", local: "data/generated/db/scripts/php/getElevationDetails.generated.json", fallback: "data/reconstructed/db/scripts/php/getElevationDetails.reconstructed.json", format: "json", status: "generated" },
        { match: "/db/scripts/php/getElevationElements.php", local: "data/generated/db/scripts/php/getElevationElements.generated.json", fallback: "data/reconstructed/db/scripts/php/getElevationElements.reconstructed.json", format: "json", status: "generated" },
        { match: "/db/scripts/php/getElevationSchemes.php", local: "data/generated/db/scripts/php/getElevationSchemes.generated.json", fallback: "data/reconstructed/db/scripts/php/getElevationSchemes.reconstructed.json", format: "json", status: "generated" },
        { match: "/db/scripts/php/getPlanFloorplans.php", local: "data/generated/db/scripts/php/getPlanFloorplans.generated.json", fallback: "data/reconstructed/db/scripts/php/getPlanFloorplans.reconstructed.json", format: "json", status: "generated" },
        { match: "/db/scripts/php/getelevnbrhoods.php", local: "data/generated/db/scripts/php/getelevnbrhoods.generated.json", fallback: "data/reconstructed/db/scripts/php/getelevnbrhoods.reconstructed.json", format: "json", status: "generated" },
        { match: "/db/scripts/php/getinteriors.php", local: "data/generated/db/scripts/php/getinteriors.generated.xml", fallback: "data/reconstructed/db/scripts/php/getinteriors.reconstructed.xml", format: "xml", status: "generated" },
        { match: "/api/v1/fp/", local: "data/generated/rendering-api/floorplan-uri.generated.txt", fallback: "data/reconstructed/rendering-api/floorplan-uri.reconstructed.txt", format: "text", status: "generated" },
        { match: "/php/getfavs.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, data: [], favorites: [] } },
        { match: "/php/uploadDeviceFavs.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, data: [] } },
        { match: "/php/addfav.php", mock: true, format: "text", status: "mocked", body: "OK mocked favorite add" },
        { match: "/php/updfav.php", mock: true, format: "text", status: "mocked", body: "OK mocked favorite update" },
        { match: "/php/delfav.php", mock: true, format: "text", status: "mocked", body: "OK mocked favorite delete" },
        { match: "/php/addfavfpopt.php", mock: true, format: "text", status: "mocked", body: "OK mocked favorite floorplan option add" },
        { match: "/php/delfavfpopt.php", mock: true, format: "text", status: "mocked", body: "OK mocked favorite floorplan option delete" },
        { match: "/php/updfavfp.php", mock: true, format: "text", status: "mocked", body: "OK mocked favorite floorplan update" },
        { match: "/php/addfavpalsel.php", mock: true, format: "text", status: "mocked", body: "OK mocked favorite palette selection" },
        { match: "/php/addcustomscheme.php", mock: true, format: "text", status: "mocked", body: "OK mocked custom scheme" },
        { match: "/php/getfavfp.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, data: [] } },
        { match: "/php/getfavfpopts.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, data: [] } },
        { match: "/php/getfavpalsel.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, data: [] } },
        { match: "/php/getfavcustomscheme.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, data: [] } },
        { match: "/php/authenMe.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, authenticated: false, user: null, message: "Local mock auth only" } },
        { match: "/php/registerMe.php", mock: true, format: "text", status: "mocked", body: "OK mocked registration" },
        { match: "/php/resetMe.php", mock: true, format: "text", status: "mocked", body: "OK mocked password reset" },
        { match: "/php/findProspectEmail.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, exists: false, data: [] } },
        { match: "/php/sendMail.php", mock: true, format: "text", status: "mocked", body: "OK mocked email" },
        { match: "/php/sendRegMail.php", mock: true, format: "text", status: "mocked", body: "OK mocked registration email" },
        { match: "/php/curlCrmSubmission.php", mock: true, format: "text", status: "mocked", body: "OK mocked CRM submission" },
        { match: "/php/createBrochureHtml.php", mock: true, format: "text", status: "mocked", body: "mock-brochure.html" },
        { match: "/php/postFiles.php", mock: true, format: "text", status: "mocked", body: "OK mocked brochure files" },
        { match: "/php/postFile.php", mock: true, format: "text", status: "mocked", body: "OK mocked brochure file" },
        { match: "/php/getCloudInventoryPhotoFileNames.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, fileNames: [] } },
        { match: "/php/mls/mls.photos.phrets.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true } },
        { match: "/src/idash/dist/php/getCloudInventoryPhotoFileNames.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true, fileNames: [] } },
        { match: "/src/idash/dist/php/mls/mls.photos.phrets.php", mock: true, format: "json", status: "mocked", response: { status: "mocked", ok: true } }
      ]
    }
  };
}(window));
